package dns_test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/lexfrei/cloudflare-tunnel-gateway-controller/internal/dns"
)

func TestDetectClusterDomain(t *testing.T) {
	t.Parallel()

	// This test verifies the public API works.
	// The actual detection depends on /etc/resolv.conf which varies by environment.
	// We just verify it doesn't panic and returns valid types.
	domain, found := dns.DetectClusterDomain()
	t.Logf("DetectClusterDomain() = %q, found = %v", domain, found)

	// If found, domain should not be empty
	if found && domain == "" {
		t.Error("DetectClusterDomain() found=true but domain is empty")
	}
}

func TestDetectClusterDomainFromFile(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name       string
		content    string
		expected   string
		shouldFind bool
	}{
		{
			name: "standard resolv.conf",
			content: `# Generated by NetworkManager
nameserver 10.96.0.10
search default.svc.cluster.local svc.cluster.local cluster.local
options ndots:5
`,
			expected:   "cluster.local",
			shouldFind: true,
		},
		{
			name: "custom cluster domain",
			content: `nameserver 10.0.0.10
search myapp.svc.custom.domain svc.custom.domain custom.domain
options ndots:2
`,
			expected:   "custom.domain",
			shouldFind: true,
		},
		{
			name: "resolv.conf with comments",
			content: `# This is a comment
; Another comment style
nameserver 8.8.8.8

search test.svc.k8s.internal svc.k8s.internal k8s.internal
`,
			expected:   "k8s.internal",
			shouldFind: true,
		},
		{
			name: "no search directive",
			content: `nameserver 8.8.8.8
nameserver 8.8.4.4
`,
			expected:   "",
			shouldFind: false,
		},
		{
			name: "search without svc domain",
			content: `nameserver 10.0.0.1
search example.com corp.local
`,
			expected:   "",
			shouldFind: false,
		},
		{
			name:       "empty file",
			content:    "",
			expected:   "",
			shouldFind: false,
		},
		{
			// resolv.conf(5): when search appears more than once, the
			// resolver uses the last instance.
			name: "multiple search lines takes the last",
			content: `nameserver 10.96.0.10
search first.svc.domain1.local svc.domain1.local
search second.svc.domain2.local svc.domain2.local
`,
			expected:   "domain2.local",
			shouldFind: true,
		},
		{
			name: "last search line without svc domain overrides an earlier one",
			content: `search default.svc.cluster.local svc.cluster.local
search example.com
`,
			expected:   "",
			shouldFind: false,
		},
		{
			// domain and search are mutually exclusive; the last one wins.
			name: "domain directive after search replaces the search list",
			content: `search default.svc.cluster.local svc.cluster.local
domain example.com
`,
			expected:   "",
			shouldFind: false,
		},
		{
			// A domain directive names one domain; tokens after it are ignored.
			name:       "domain directive takes only its first token",
			content:    "domain example.com svc.cluster.local\n",
			expected:   "",
			shouldFind: false,
		},
		{
			name:       "domain keyword with no domain leaves the search list alone",
			content:    "search default.svc.cluster.local svc.cluster.local\ndomain\n",
			expected:   "cluster.local",
			shouldFind: true,
		},
		{
			name:       "CRLF line endings",
			content:    "nameserver 10.96.0.10\r\nsearch default.svc.cluster.local svc.cluster.local cluster.local\r\n",
			expected:   "cluster.local",
			shouldFind: true,
		},
		{
			name:       "tab after the search keyword",
			content:    "search\tdefault.svc.cluster.local\tsvc.cluster.local\n",
			expected:   "cluster.local",
			shouldFind: true,
		},
		{
			name:       "leading whitespace",
			content:    "  search default.svc.cluster.local svc.cluster.local\n",
			expected:   "cluster.local",
			shouldFind: true,
		},
		{
			name:       "trailing root dot is dropped",
			content:    "search default.svc.cluster.local. svc.cluster.local. cluster.local.\n",
			expected:   "cluster.local",
			shouldFind: true,
		},
		{
			name:       "search keyword with no domains",
			content:    "search\n",
			expected:   "",
			shouldFind: false,
		},
		{
			name:       "bare svc labels are skipped for a later cluster domain",
			content:    "search svc. svc.. svc.cluster.local\n",
			expected:   "cluster.local",
			shouldFind: true,
		},
		{
			name:       "commented-out search line is ignored",
			content:    "# search default.svc.cluster.local svc.cluster.local\n",
			expected:   "",
			shouldFind: false,
		},
		{
			// bufio.Scanner stops at a line longer than its buffer; a file
			// that could not be read to the end is not trusted.
			name:       "unreadable line after a search directive",
			content:    "search svc.cluster.local\n" + strings.Repeat("x", 70*1024) + "\n",
			expected:   "",
			shouldFind: false,
		},
	}

	for _, testCase := range tests {
		t.Run(testCase.name, func(t *testing.T) {
			t.Parallel()

			// Create temp file with test content
			tmpDir := t.TempDir()
			tmpFile := filepath.Join(tmpDir, "resolv.conf")

			err := os.WriteFile(tmpFile, []byte(testCase.content), 0o600)
			if err != nil {
				t.Fatalf("failed to write temp file: %v", err)
			}

			result, found := dns.DetectClusterDomainFromFile(tmpFile)

			if found != testCase.shouldFind {
				t.Errorf("DetectClusterDomainFromFile() found = %v, want %v", found, testCase.shouldFind)
			}

			if result != testCase.expected {
				t.Errorf("DetectClusterDomainFromFile() = %q, want %q", result, testCase.expected)
			}
		})
	}
}

func TestDetectClusterDomainFromFile_NonExistent(t *testing.T) {
	t.Parallel()

	result, found := dns.DetectClusterDomainFromFile("/nonexistent/path/resolv.conf")

	if found {
		t.Error("DetectClusterDomainFromFile() should return false for non-existent file")
	}

	if result != "" {
		t.Errorf("DetectClusterDomainFromFile() = %q, want empty string", result)
	}
}
