package config

import (
	"context"

	"github.com/cockroachdb/errors"
	apierrors "k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/types"
	gatewayv1 "sigs.k8s.io/gateway-api/apis/v1"

	"github.com/lexfrei/cloudflare-tunnel-gateway-controller/api/v1alpha1"
	"github.com/lexfrei/cloudflare-tunnel-gateway-controller/internal/render"
	"github.com/lexfrei/cloudflare-tunnel-gateway-controller/internal/tunnel"
)

// GatewayParametersRefKind is the Gateway.spec.infrastructure.parametersRef
// kind that opts a Gateway into a dedicated data plane.
const GatewayParametersRefKind = "GatewayConfig"

// Default Secret keys for the per-Gateway secrets, matching the chart's
// conventions for the shared proxy.
const (
	tunnelTokenSecretKey = "tunnel-token"
	authTokenSecretKey   = "auth-token"
	apiTokenSecretKey    = "api-token"
)

// ErrInvalidParameters classifies a Gateway whose
// infrastructure.parametersRef cannot be honoured for a DETERMINISTIC,
// user-fixable reason: unsupported group/kind, NotFound referents, a missing
// Secret key, or a connector token that does not parse. The Gateway
// reconciler maps it onto Accepted=False with reason InvalidParameters, the
// condition shape the Gateway API recommends for this failure class.
// Transient infrastructure failures (apiserver timeouts, throttling) are
// deliberately NOT wrapped with this sentinel — they must keep their own
// identity so callers retry with backoff instead of blaming the user's spec.
var ErrInvalidParameters = errors.New("invalid infrastructure parametersRef")

// PerGatewayConfig is the resolution result for a Gateway opted into a
// dedicated data plane via infrastructure.parametersRef.
type PerGatewayConfig struct {
	// ResolvedConfig carries what the Cloudflare ingress sync needs: the API
	// token (override or class fallback) plus the tunnel identity PARSED from
	// the connector token — the tunnel always belongs to the token's account,
	// so AccountID is the token's account tag, never the class setting.
	ResolvedConfig

	// TunnelToken is the raw connector token handed to the rendered proxy
	// pods via their token Secret.
	TunnelToken string

	// TunnelTokenSecret names the token Secret (Gateway namespace) for watch
	// and rotation-hash purposes.
	TunnelTokenSecret types.NamespacedName

	// AuthToken optionally protects the per-Gateway proxy config API; the
	// controller authenticates its pushes with it. Empty = no auth.
	AuthToken string

	// GatewayConfig is the source object carrying the render knobs
	// (replicas, autoscaling, resources, image).
	GatewayConfig *v1alpha1.GatewayConfig
}

// HasInfrastructureParametersRef reports whether the Gateway opts into a
// per-Gateway data plane. It deliberately does not validate the ref — an
// unsupported group/kind is still an opt-in attempt and must surface as
// InvalidParameters rather than silently falling back to the shared plane.
func HasInfrastructureParametersRef(gateway *gatewayv1.Gateway) bool {
	return gateway.Spec.Infrastructure != nil && gateway.Spec.Infrastructure.ParametersRef != nil
}

// ResolveForGateway resolves the per-Gateway data-plane configuration. A
// Gateway without infrastructure.parametersRef returns (nil, nil) — shared
// mode, byte-for-byte the pre-existing behaviour. Resolution failures caused
// by the referenced material classify as ErrInvalidParameters (see the
// sentinel's doc for the status mapping).
func (r *Resolver) ResolveForGateway(
	ctx context.Context,
	gateway *gatewayv1.Gateway,
) (*PerGatewayConfig, error) {
	base, err := r.resolveStatusConfig(ctx, gateway)
	if err != nil || base == nil {
		return base, err
	}

	authToken, err := r.readAuthToken(ctx, gateway, base.GatewayConfig)
	if err != nil {
		return nil, err
	}

	base.AuthToken = authToken

	return base, nil
}

// ResolveStatusConfigForGateway resolves everything the Gateway STATUS path
// needs — the ResolvedConfig (tunnel identity + API token), the source
// GatewayConfig, and the connector token — but NOT the config-API auth token.
// The auth token's Secret is generated by the infra reconciler, so reading it
// on the status path would fail transiently during the bootstrap window between
// opt-in and the Secret's creation, leaving the Gateway with NO status
// conditions until the Secret lands. Status reporting must not depend on a
// render-side Secret it never consumes. Returns (nil, nil) for shared mode,
// like ResolveForGateway.
func (r *Resolver) ResolveStatusConfigForGateway(
	ctx context.Context,
	gateway *gatewayv1.Gateway,
) (*PerGatewayConfig, error) {
	return r.resolveStatusConfig(ctx, gateway)
}

// resolveStatusConfig is the shared core: it resolves the ResolvedConfig and
// the connector token but leaves AuthToken empty. ResolveForGateway layers the
// auth-token read on top; ResolveStatusConfigForGateway returns it as-is.
func (r *Resolver) resolveStatusConfig(
	ctx context.Context,
	gateway *gatewayv1.Gateway,
) (*PerGatewayConfig, error) {
	if !HasInfrastructureParametersRef(gateway) {
		return nil, nil //nolint:nilnil // nil,nil IS the shared-mode signal, documented contract
	}

	gwConfig, err := r.getGatewayConfig(ctx, gateway)
	if err != nil {
		return nil, err
	}

	token, tokenSecretName, err := r.readTunnelToken(ctx, gateway.Namespace, gwConfig)
	if err != nil {
		return nil, err
	}

	parsed, err := tunnel.ParseTunnelToken(token)
	if err != nil {
		return nil, errors.Wrapf(ErrInvalidParameters,
			"tunnel token in secret %s/%s does not parse: %v", gateway.Namespace, tokenSecretName.Name, err)
	}

	apiToken, err := r.resolveGatewayAPIToken(ctx, gateway, gwConfig)
	if err != nil {
		return nil, err
	}

	return &PerGatewayConfig{
		ResolvedConfig: ResolvedConfig{
			APIToken: apiToken,
			// The tunnel lives in the token's account by construction.
			AccountID:  parsed.AccountTag,
			TunnelID:   parsed.TunnelID.String(),
			ConfigName: "gatewayconfig:" + gwConfig.Namespace + "/" + gwConfig.Name,
		},
		TunnelToken:       token,
		TunnelTokenSecret: tokenSecretName,
		GatewayConfig:     gwConfig,
	}, nil
}

// GetGatewayConfig resolves and returns the GatewayConfig referenced by the
// Gateway's infrastructure.parametersRef, applying the same group/kind
// validation and ErrInvalidParameters classification as ResolveForGateway.
// Exposed for the infra reconciler, which must ensure the generated auth
// Secret exists BEFORE ResolveForGateway can read it.
func (r *Resolver) GetGatewayConfig(
	ctx context.Context,
	gateway *gatewayv1.Gateway,
) (*v1alpha1.GatewayConfig, error) {
	return r.getGatewayConfig(ctx, gateway)
}

// getGatewayConfig validates the parametersRef group/kind and fetches the
// referent from the Gateway's namespace (LocalParametersReference is
// namespace-local by spec).
func (r *Resolver) getGatewayConfig(
	ctx context.Context,
	gateway *gatewayv1.Gateway,
) (*v1alpha1.GatewayConfig, error) {
	ref := gateway.Spec.Infrastructure.ParametersRef

	if string(ref.Group) != ParametersRefGroup || string(ref.Kind) != GatewayParametersRefKind {
		return nil, errors.Wrapf(ErrInvalidParameters,
			"unsupported infrastructure parametersRef %s/%s (expected %s/%s)",
			ref.Group, ref.Kind, ParametersRefGroup, GatewayParametersRefKind)
	}

	gwConfig := &v1alpha1.GatewayConfig{}

	err := r.client.Get(ctx, types.NamespacedName{Name: ref.Name, Namespace: gateway.Namespace}, gwConfig)
	if err != nil {
		// Only a deterministic referent failure is the USER's parametersRef
		// being invalid; a transient apiserver error keeps its own identity so
		// callers retry with backoff instead of stamping InvalidParameters.
		if apierrors.IsNotFound(err) {
			return nil, errors.Wrapf(ErrInvalidParameters,
				"GatewayConfig %s/%s: %v", gateway.Namespace, ref.Name, err)
		}

		return nil, errors.Wrapf(err, "reading GatewayConfig %s/%s", gateway.Namespace, ref.Name)
	}

	return gwConfig, nil
}

// readTunnelToken fetches the connector token from the namespace-local Secret.
func (r *Resolver) readTunnelToken(
	ctx context.Context,
	namespace string,
	gwConfig *v1alpha1.GatewayConfig,
) (string, types.NamespacedName, error) {
	ref := gwConfig.Spec.TunnelTokenSecretRef
	secretName := types.NamespacedName{Name: ref.Name, Namespace: namespace}

	secret, err := r.getSecret(ctx, ref.Name, namespace)
	if err != nil {
		if apierrors.IsNotFound(err) {
			return "", secretName, errors.Wrapf(ErrInvalidParameters,
				"tunnel token secret %s/%s: %v", namespace, ref.Name, err)
		}

		return "", secretName, errors.Wrapf(err, "reading tunnel token secret %s/%s", namespace, ref.Name)
	}

	key := ref.KeyOr(tunnelTokenSecretKey)

	token := secret.Data[key]
	if len(token) == 0 {
		return "", secretName, errors.Wrapf(ErrInvalidParameters,
			"tunnel token secret %s/%s has no %q key (or it is empty)", namespace, ref.Name, key)
	}

	return string(token), secretName, nil
}

// resolveGatewayAPIToken returns the Cloudflare API token for the Gateway's
// tunnel-document writes: the GatewayConfig-level override when set (read
// from the GatewayConfig's OWN namespace only), otherwise the token resolved
// from the Gateway's GatewayClass → GatewayClassConfig chain.
func (r *Resolver) resolveGatewayAPIToken(
	ctx context.Context,
	gateway *gatewayv1.Gateway,
	gwConfig *v1alpha1.GatewayConfig,
) (string, error) {
	if override := gwConfig.Spec.CloudflareCredentialsSecretRef; override != nil {
		return r.readCredentialOverride(ctx, gwConfig, override)
	}

	classResolved, err := r.ResolveFromGatewayClassName(ctx, string(gateway.Spec.GatewayClassName))
	if err != nil {
		// Only genuinely-retryable apiserver failures (timeout, throttling,
		// 5xx) keep backing off without stamping the Gateway. EVERY other
		// class-chain failure is a deterministic, user-fixable config problem
		// (missing/invalid parametersRef, absent GatewayClassConfig or its
		// Secret, empty tunnelID, empty api-token key) — the per-Gateway plane
		// can never write its tunnel document, so classify it as
		// ErrInvalidParameters and surface Accepted=False instead of backing
		// off forever with no status. ResolveFromGatewayClassName only reads
		// Kubernetes objects (no Cloudflare-API account auto-detection happens
		// on this token-only path), so the retryable arm is purely about
		// transient apiserver reads and self-heals on the next reconcile.
		if isRetryableAPIError(err) {
			return "", errors.Wrap(err, "resolving class credentials for per-Gateway data plane")
		}

		return "", errors.Wrapf(ErrInvalidParameters,
			"class credentials for per-Gateway data plane: %v", err)
	}

	return classResolved.APIToken, nil
}

// isRetryableAPIError reports whether err is a transient apiserver failure that
// warrants backoff rather than a deterministic, user-fixable config error.
func isRetryableAPIError(err error) bool {
	return apierrors.IsServerTimeout(err) ||
		apierrors.IsTimeout(err) ||
		apierrors.IsTooManyRequests(err) ||
		apierrors.IsInternalError(err) ||
		apierrors.IsServiceUnavailable(err)
}

// readCredentialOverride fetches the GatewayConfig-level Cloudflare API
// token. The Secret is read from the GatewayConfig's OWN namespace only —
// the reference type carries no namespace by design (tenancy boundary).
func (r *Resolver) readCredentialOverride(
	ctx context.Context,
	gwConfig *v1alpha1.GatewayConfig,
	override *v1alpha1.LocalSecretReference,
) (string, error) {
	namespace := gwConfig.Namespace

	secret, err := r.getSecret(ctx, override.Name, namespace)
	if err != nil {
		if apierrors.IsNotFound(err) {
			return "", errors.Wrapf(ErrInvalidParameters,
				"cloudflare credentials secret %s/%s: %v", namespace, override.Name, err)
		}

		return "", errors.Wrapf(err, "reading cloudflare credentials secret %s/%s", namespace, override.Name)
	}

	key := override.KeyOr(apiTokenSecretKey)

	token := secret.Data[key]
	if len(token) == 0 {
		return "", errors.Wrapf(ErrInvalidParameters,
			"cloudflare credentials secret %s/%s has no %q key (or it is empty)", namespace, override.Name, key)
	}

	return string(token), nil
}

// readAuthToken resolves the config-API bearer token. Push auth is NEVER
// optional: without an explicit authTokenSecretRef the token comes from the
// controller-generated Secret (render.GeneratedAuthSecretName), so a tenant
// data plane is never rendered or pushed to without authentication — an
// unauthenticated config API would accept PUT /config from any pod that can
// reach it. An absent explicit Secret is a user spec error
// (ErrInvalidParameters); an absent GENERATED Secret is the bootstrap window
// before the infra reconciler creates it — transient, so callers retry
// instead of stamping InvalidParameters on a healthy spec.
func (r *Resolver) readAuthToken(
	ctx context.Context,
	gateway *gatewayv1.Gateway,
	gwConfig *v1alpha1.GatewayConfig,
) (string, error) {
	namespace := gateway.Namespace

	name, key := render.GeneratedAuthSecretName(gateway), authTokenSecretKey
	generated := true

	if ref := gwConfig.Spec.AuthTokenSecretRef; ref != nil {
		name, key, generated = ref.Name, ref.KeyOr(authTokenSecretKey), false
	}

	secret, err := r.getSecret(ctx, name, namespace)
	if err != nil {
		if apierrors.IsNotFound(err) && generated {
			// Bootstrap window: keep the error's own identity for backoff.
			return "", errors.Wrapf(err,
				"generated auth token secret %s/%s not yet created", namespace, name)
		}

		if apierrors.IsNotFound(err) {
			return "", errors.Wrapf(ErrInvalidParameters,
				"auth token secret %s/%s: %v", namespace, name, err)
		}

		return "", errors.Wrapf(err, "reading auth token secret %s/%s", namespace, name)
	}

	token := secret.Data[key]
	if len(token) == 0 {
		return "", errors.Wrapf(ErrInvalidParameters,
			"auth token secret %s/%s has no %q key (or it is empty)", namespace, name, key)
	}

	return string(token), nil
}
